### ISSUE TITLE
TypeError: css/html is not a function - Card broken after HA 2026.4.x update (lit compatibility)

### ISSUE THREAD

**Issue by Nero201988** [pacemaker82/Compact-Power-Card#66]
**Version:** 1.3.3.8
**Home Assistant version:** 2026.4.x

**Describe the bug**
After updating Home Assistant to 2026.4.x, the card no longer renders. 
The dashboard shows a configuration error and the browser console throws:

- `Uncaught TypeError: html is not a function` at CompactPowerCard.render
- `Uncaught TypeError: css is not a function` at CompactPowerCard.finalize

Both errors point to a lit-html compatibility issue introduced with the HA 2026.x update.

**To reproduce**
1. Install HA 2026.4.x
2. Open a dashboard containing compact-power-card
3. Card shows configuration error, console shows the errors above

**Expected behavior**
Card renders normally as it did before the update.

**Additional context**
Tested in Chrome and Edge - both show the same errors after clearing cache.
The card worked fine on the previous HA version.

**Comment by pacemaker82** [comment]
I am currently running 2026.4.1 with no issues. Are you on latest HA version? I didnt test with 4.0

<img width="612" height="343" alt="Image" src="https://github.com/user-attachments/assets/cafa2ea8-62cd-44b4-8a1f-1e1d4dac0ff5" />

**Comment by pacemaker82** [comment]
Just in case, I've adjusted the way it resolves Lit to see if that helps. It works fine for me before and after this change, so hard for me to tell ... 

https://github.com/pacemaker82/Compact-Power-Card/releases/tag/v1.3.3.9

Can you get back to me?

**Comment by Nero201988** [comment]
> Just in case, I've adjusted the way it resolves Lit to see if that helps. It works fine for me before and after this change, so hard for me to tell ...
> 
> https://github.com/pacemaker82/Compact-Power-Card/releases/tag/v1.3.3.9
> 
> Can you get back to me?

Thanks for the quick fix! I'm running HA 2026.4.1 and v1.3.3.9 resolves 
the issue completely. Card loads perfectly again without any errors.

P.S. Since we're in touch — would it be possible to support a topology 
where PV only connects to the battery, and the battery then feeds the 
house and/or grid? So the flow would be:

PV → Battery → House
PV → Battery → Grid

Without a direct PV → House connection. My system is physically wired 
this way (Growatt NOAH 2000) and right now I can't reflect this accurately 
in the card. Would love to have this as a configurable option!
